"""Agent Module E: AI-Generated Code Specific Vulnerabilities Scanner."""

from __future__ import annotations

import re
from pathlib import Path
from typing import List

import tree_sitter
import tree_sitter_python
from guardrail.cli import collect_project_files
from guardrail.models import Finding, Severity

# Hallucinated or non-existent security libraries/methods frequently outputted by LLMs
HALLUCINATED_SECURITY_PATTERNS = {
    "crypto.safe_encrypt": "Calling non-existent function 'crypto.safe_encrypt'.",
    "jwt.verify_signature_auto": "Calling non-existent function 'jwt.verify_signature_auto'.",
    "security.validate_token_all": "Calling fictitious 'security.validate_token_all' method.",
    "hashlib.sha256_decrypt": "Calling impossible function 'sha256_decrypt' (SHA256 is an irreversible one-way hash).",
    "auth.auto_authenticate": "Calling hallucinated 'auth.auto_authenticate' function.",
}

INSECURE_AI_DEFAULTS = [
    (r"(?i)\bdebug\s*=\s*True\b", "AI Insecure Default: debug=True enabled in production configuration.", Severity.WARNING),
    (r"(?i)secret_key\s*=\s*['\"](?:secret|change_me|your_secret_key|default|12345)['\"]", "AI Insecure Default: Predictable dummy secret_key introduced by AI code generation.", Severity.ERROR),
    (r"(?i)password\s*=\s*['\"](?:password|admin|root|123456)['\"]", "AI Insecure Default: Hardcoded trivial password.", Severity.ERROR),
    (r"\bverify\s*=\s*False\b", "AI Insecure Default: Disabled TLS/SSL verification (verify=False) in HTTP client call.", Severity.ERROR),
]


class AiCodeChecksScanner:
    """Detects vibe-coded logic flaws, hallucinated security functions, and insecure defaults generated by AI assistants."""

    def __init__(self, exclude_patterns: List[str] = None):
        self.exclude_patterns = exclude_patterns or [
            ".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache"
        ]
        self._language = tree_sitter.Language(tree_sitter_python.language())
        self._parser = tree_sitter.Parser(self._language)

    def scan_directory(self, root: Path) -> List[Finding]:
        findings: List[Finding] = []
        files = collect_project_files(root, self.exclude_patterns)

        for file_path in files:
            rel_path = str(file_path.relative_to(root)).replace("\\", "/")
            if file_path.suffix == ".py":
                try:
                    findings.extend(self._analyze_file(file_path, rel_path))
                except Exception:
                    pass

        return findings

    def _analyze_file(self, file_path: Path, rel_path: str) -> List[Finding]:
        findings: List[Finding] = []
        code_bytes = file_path.read_bytes()
        code_text = code_bytes.decode("utf-8", errors="replace")
        lines = code_text.splitlines()

        tree = self._parser.parse(code_bytes)

        def get_snippet(line_idx: int) -> str:
            if 0 <= line_idx < len(lines):
                return lines[line_idx].strip()[:100]
            return ""

        # 1. AST based checks (Vibe-coded bypasses & Hallucinations)
        def traverse(node: tree_sitter.Node):
            # Vibe-coded check: Call expression as a standalone statement without checking return value
            # e.g., expression_statement -> call where function is verify_password or check_token
            if node.type == "expression_statement":
                child = node.children[0] if node.children else None
                if child and child.type == "call":
                    fn = child.child_by_field_name("function")
                    if fn:
                        fn_name = fn.text.decode("utf-8")
                        if any(v in fn_name.lower() for v in ("check_password", "verify_password", "verify_token", "authenticate_user")):
                            findings.append(Finding(
                                rule_id="AI-VIBE-AUTH-BYPASS",
                                analyzer="AiCodeChecksScanner",
                                severity=Severity.ERROR,
                                message=f"Vibe-Coded Auth Bypass: Security function '{fn_name}()' executed as standalone statement without verifying return value.",
                                file_path=rel_path,
                                line_number=node.start_point[0] + 1,
                                snippet=get_snippet(node.start_point[0])
                            ))

            # Hallucinated security functions
            if node.type == "call":
                fn = node.child_by_field_name("function")
                if fn:
                    fn_text = fn.text.decode("utf-8")
                    for hall, desc in HALLUCINATED_SECURITY_PATTERNS.items():
                        if hall in fn_text:
                            findings.append(Finding(
                                rule_id="AI-HALLUCINATED-SECURITY-API",
                                analyzer="AiCodeChecksScanner",
                                severity=Severity.ERROR,
                                message=f"AI Hallucinated Security API: {desc}",
                                file_path=rel_path,
                                line_number=node.start_point[0] + 1,
                                snippet=get_snippet(node.start_point[0])
                            ))

            # Over-permissive database queries in strings
            if node.type == "string":
                text = node.text.decode("utf-8")
                if "select * from" in text.lower():
                    # check if on sensitive table without WHERE
                    for sensitive_tbl in ("users", "accounts", "tokens", "credentials", "passwords", "payments"):
                        if f"from {sensitive_tbl}" in text.lower() and "where" not in text.lower():
                            findings.append(Finding(
                                rule_id="AI-OVERPERMISSIVE-QUERY",
                                analyzer="AiCodeChecksScanner",
                                severity=Severity.WARNING,
                                message=f"Over-permissive AI query: 'SELECT * FROM {sensitive_tbl}' without WHERE filter.",
                                file_path=rel_path,
                                line_number=node.start_point[0] + 1,
                                snippet=get_snippet(node.start_point[0])
                            ))

            for c in node.children:
                traverse(c)

        traverse(tree.root_node)

        # 2. Insecure Defaults Check
        for idx, line in enumerate(lines, 1):
            for pat, msg, sev in INSECURE_AI_DEFAULTS:
                if re.search(pat, line):
                    findings.append(Finding(
                        rule_id="AI-INSECURE-DEFAULT",
                        analyzer="AiCodeChecksScanner",
                        severity=sev,
                        message=msg,
                        file_path=rel_path,
                        line_number=idx,
                        snippet=line.strip()[:100]
                    ))

        return findings
