"""Git diff parser and dependency/code modification tracker.

Extracts modified files, added line numbers, and newly introduced dependencies
from git diffs or local working tree changes.
"""

from __future__ import annotations

import os
import re
import subprocess
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple


@dataclass
class AddedLine:
    line_number: int
    content: str


@dataclass
class FileDiff:
    path: str
    status: str  # 'added', 'modified', 'deleted'
    added_lines: List[AddedLine] = field(default_factory=list)

    @property
    def added_line_numbers(self) -> Set[int]:
        return {line.line_number for line in self.added_lines}


@dataclass
class DependencyChange:
    package_name: str
    specifier: str
    source_file: str
    line_number: Optional[int] = None


@dataclass
class DiffResult:
    files: Dict[str, FileDiff] = field(default_factory=dict)
    new_dependencies: List[DependencyChange] = field(default_factory=list)

    def is_line_added(self, file_path: str, line_number: int) -> bool:
        normalized = file_path.replace("\\", "/")
        for path, file_diff in self.files.items():
            if path.replace("\\", "/") == normalized:
                return line_number in file_diff.added_line_numbers
        return False


def run_git_command(args: List[str], cwd: Optional[Path | str] = None) -> Optional[str]:
    """Execute a git command and return stdout as string, or None if git fails."""
    try:
        proc = subprocess.run(
            ["git"] + args,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode == 0:
            return proc.stdout
        return None
    except Exception:
        return None


def parse_unified_diff(diff_text: str) -> Dict[str, FileDiff]:
    """
    Parse unified diff text (such as generated by git diff) into structured FileDiffs.
    Accurately maps line numbers for added lines.
    """
    files: Dict[str, FileDiff] = {}
    current_file: Optional[str] = None
    current_status = "modified"
    current_line_num = 0
    in_hunk = False

    diff_git_re = re.compile(r"^diff --git a/(.*) b/(.*)$")
    new_file_re = re.compile(r"^new file mode")
    deleted_file_re = re.compile(r"^deleted file mode")
    hunk_re = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")

    for line in diff_text.splitlines():
        match_git = diff_git_re.match(line)
        if match_git:
            b_path = match_git.group(2)
            current_file = b_path
            current_status = "modified"
            in_hunk = False
            files[current_file] = FileDiff(path=current_file, status=current_status)
            continue

        if current_file is None:
            continue

        if new_file_re.match(line):
            current_status = "added"
            files[current_file].status = current_status
            continue

        if deleted_file_re.match(line):
            current_status = "deleted"
            files[current_file].status = current_status
            continue

        hunk_match = hunk_re.match(line)
        if hunk_match:
            in_hunk = True
            current_line_num = int(hunk_match.group(1))
            continue

        if in_hunk:
            if line.startswith("+") and not line.startswith("+++"):
                content = line[1:]
                files[current_file].added_lines.append(
                    AddedLine(line_number=current_line_num, content=content)
                )
                current_line_num += 1
            elif line.startswith("-") and not line.startswith("---"):
                pass
            elif line.startswith(" "):
                current_line_num += 1
            elif line.startswith("\\"):
                pass

    return files


def extract_package_from_requirement_line(line: str) -> Optional[Tuple[str, str]]:
    """
    Extract package name and version specifier from a requirements.txt or pyproject line.
    Handles PEP 508 strings, e.g. "requests>=2.28.0", "pydantic~=2.0", "flask[async]".
    """
    cleaned = line.strip().strip('"').strip("'")
    if "#" in cleaned:
        cleaned = cleaned.split("#", 1)[0].strip()
    if not cleaned:
        return None
    if cleaned.startswith(("-r", "-f", "-i", "--extra-index-url", "--index-url")):
        return None

    # Matches package name: alphanumeric, hyphen, underscore, dot, optional extras [async,crypto]
    match = re.match(r"^([A-Za-z0-9_.\-]+)(?:\[[^\]]+\])?\s*([<>=!~].*)?$", cleaned)
    if match:
        pkg_name = match.group(1).lower().replace("_", "-")
        # Validate that package name starts with a letter or digit and is not just numbers/dots/version
        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9_.\-]*$", pkg_name):
            return None
        # Avoid version numbers mistaken for package name
        if re.match(r"^\d+(\.\d+)*$", pkg_name):
            return None
        specifier = match.group(2).strip() if match.group(2) else ""
        return pkg_name, specifier
    return None


def extract_dependencies_from_pyproject_toml(content: str, source_file: str) -> List[DependencyChange]:
    """Parse a pyproject.toml string using tomllib and extract genuine dependencies."""
    deps: List[DependencyChange] = []
    seen: Set[str] = set()

    try:
        data = tomllib.loads(content)
    except Exception:
        return deps

    raw_dep_strings: List[str] = []

    # 1. PEP 621: [project.dependencies]
    proj_deps = data.get("project", {}).get("dependencies", [])
    if isinstance(proj_deps, list):
        raw_dep_strings.extend(proj_deps)

    # 2. PEP 621: [project.optional-dependencies]
    opt_deps = data.get("project", {}).get("optional-dependencies", {})
    if isinstance(opt_deps, dict):
        for group, group_deps in opt_deps.items():
            if isinstance(group_deps, list):
                raw_dep_strings.extend(group_deps)

    # 3. Poetry: [tool.poetry.dependencies]
    poetry_deps = data.get("tool", {}).get("poetry", {}).get("dependencies", {})
    if isinstance(poetry_deps, dict):
        for pkg, spec in poetry_deps.items():
            if pkg.lower() != "python":
                raw_dep_strings.append(f"{pkg} {spec}")

    for raw in raw_dep_strings:
        res = extract_package_from_requirement_line(str(raw))
        if res:
            pkg, spec = res
            if pkg not in seen:
                seen.add(pkg)
                deps.append(
                    DependencyChange(
                        package_name=pkg,
                        specifier=spec,
                        source_file=source_file,
                    )
                )

    return deps


def extract_dependencies_from_diff(files: Dict[str, FileDiff]) -> List[DependencyChange]:
    """Scan added lines in dependency definition files to find newly introduced packages."""
    new_deps: List[DependencyChange] = []
    seen: Set[str] = set()

    for path, fdiff in files.items():
        filename = Path(path).name.lower()

        # Check requirements*.txt
        if filename.startswith("requirements") and filename.endswith(".txt"):
            for added in fdiff.added_lines:
                res = extract_package_from_requirement_line(added.content)
                if res:
                    pkg, spec = res
                    if pkg not in seen:
                        seen.add(pkg)
                        new_deps.append(
                            DependencyChange(
                                package_name=pkg,
                                specifier=spec,
                                source_file=path,
                                line_number=added.line_number,
                            )
                        )

        # Check pyproject.toml
        elif filename == "pyproject.toml":
            # For diff hunks, only consider lines inside dependencies = [ ... ]
            in_deps_section = False
            for added in fdiff.added_lines:
                text = added.content.strip()
                if "dependencies" in text and ("=" in text or "[" in text):
                    in_deps_section = True
                if in_deps_section:
                    if text == "]" or text == "}":
                        in_deps_section = False
                    quoted_match = re.search(r'"([^"]+)"|\'([^\']+)\'', text)
                    if quoted_match:
                        raw_spec = quoted_match.group(1) or quoted_match.group(2)
                        res = extract_package_from_requirement_line(raw_spec)
                        if res:
                            pkg, spec = res
                            if pkg not in seen:
                                seen.add(pkg)
                                new_deps.append(
                                    DependencyChange(
                                        package_name=pkg,
                                        specifier=spec,
                                        source_file=path,
                                        line_number=added.line_number,
                                    )
                                )

        # Check Pipfile
        elif filename == "pipfile":
            in_packages = False
            for added in fdiff.added_lines:
                text = added.content.strip()
                if text.startswith("[packages]") or text.startswith("[dev-packages]"):
                    in_packages = True
                    continue
                elif text.startswith("["):
                    in_packages = False
                    continue

                if in_packages:
                    pipfile_match = re.match(r'^([A-Za-z0-9_.\-]+)\s*=\s*(.+)$', text)
                    if pipfile_match:
                        pkg = pipfile_match.group(1).lower().replace("_", "-")
                        spec = pipfile_match.group(2).strip('"\'')
                        if pkg not in seen:
                            seen.add(pkg)
                            new_deps.append(
                                DependencyChange(
                                    package_name=pkg,
                                    specifier=spec,
                                    source_file=path,
                                    line_number=added.line_number,
                                )
                            )

    return new_deps


def get_git_diff(
    staged: bool = False,
    base_ref: Optional[str] = None,
    cwd: Optional[Path | str] = None,
) -> DiffResult:
    """
    Extract git diff from working directory.
    Supports staged diffs, unstaged diffs, or diffs against base branch/commit.
    """
    args = ["diff", "-U0"]
    if base_ref:
        args.append(base_ref)
    elif staged:
        args.append("--cached")
    else:
        head_check = run_git_command(["rev-parse", "--verify", "HEAD"], cwd=cwd)
        if head_check:
            args.append("HEAD")

    diff_output = run_git_command(args, cwd=cwd)
    if diff_output is None:
        return DiffResult()

    files = parse_unified_diff(diff_output)
    deps = extract_dependencies_from_diff(files)
    return DiffResult(files=files, new_dependencies=deps)
